### ISSUE TITLE
Doesn't work fine

### ISSUE THREAD

**Issue by TyrionFront** [MarcelloGhiozzi/node-telegram-login#2]
Hi !
After the installation and following attempt to use "node-telegram-login" I've been faced with next error:
```TypeError: TelegramLogin is not a constructor```.

Node v14.16.1
npm 6.14.12

**Comment by mghiozzi** [comment]
Hi Tyron!
Can you show me your code that gives you this error?
Sorry for the late response, i am really busy right now and i'm not really mantaining this package.
I'll try to update it as soon as possibile

**Comment by TyrionFront** [comment]
mghiozzi, TXS a lot 4 the response but this issue is not relevant anymore) Codebase related to it now has a completely different architecture. 
So it's ok )
